# -*- coding: utf-8 -*-
"""doodlewar2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b3beLLBAuH1GatxpKzbGhYfU-JXEhZrH
"""
import cv2 as cv2
import cloudinary
import cloudinary
import cloudinary.uploader
import cloudinary.api
cloudinary.config(
    cloud_name="dcugtsmvl",
    api_key="692466545653937",
    api_secret="Rq9IgeFEFZsr2et_hJ6orVMurgI"
)

# from google.colab.patches import cv2_imshow


# cv2_imshow(img)

# img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# cv2_imshow(img_gray)

# img_invert = cv2.bitwise_not(img_gray)

# cv2_imshow(img_invert)

# img_smoothing = cv2.GaussianBlur(img_invert, (21, 21),sigmaX=0, sigmaY=0)

# cv2_imshow(img_smoothing)


# cv2_imshow(final_img)

def generate_sketch():
    print("came to genreate image...")
    img = cv2.imread('./temp.png', 1)
    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img_invert = cv2.bitwise_not(img_gray)
    img_smoothing = cv2.GaussianBlur(img_invert, (21, 21), sigmaX=0, sigmaY=0)
    final_img = dodgeV2(img_gray, img_smoothing)
    cv2.imwrite("processed_image.png", final_img)
    print(final_img)
    uploaded_image = cloudinary.uploader.upload("processed_image.png")
    print("uploaded_image")
    print(uploaded_image)
    return uploaded_image


def dodgeV2(x, y):

    return cv2.divide(x, 255 - y, scale=256)


if __name__ == "__main__":
    img = cv2.imread('./dhoni.jpg', 1)
    generate_sketch(img)
